### PR TITLE
extend zsh and bash completion by newly added baudrates

### PR DESCRIPTION
**Pull request by Kaisrlik**
patch df62ab77f582080d8ea648da5827b32d8d9e34a9 extends support of
baudrates up to 4Mbps.

### CODE REVIEW

**Comment by Kaisrlik** [comment]
stupid me, I did a mistake in bash :(

**Comment by wentasah** [comment]
Merged. Thanks! Shall I prepare a new version of Debian package or you don't use my packages?

**Comment by Kaisrlik** [comment]
Thank you. I do not need a package.

**Comment by Cynerd** [comment]
I would appreciated tag so I can bump my version but I don't have currently need for high baudrates so no need for these changes right now. That means that you can wait for some other changes with that for now and possibly tag it later on.

**Comment by wentasah** [comment]
Tag created.

**Comment by Cynerd** [comment]
Thank you.

**Pull request merged**
